spring.application.name=sanmartin
# Configuración con tus credenciales reales de PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/Proyecto_Integrador
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

 
# Esto le dice a Spring Boot que USE tus tablas actuales en lugar de borrarlas o reescribirlas.
spring.jpa.hibernate.ddl-auto=validate


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8081