spring.application.name=sanmartin

# Configuración de conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/Proyecto_Integrador
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# CAMBIO 1: Usamos 'update' en lugar de 'validate' para que Hibernate pueda escribir cambios
# Esto permite que la aplicación gestione la persistencia con tus tablas existentes
spring.jpa.hibernate.ddl-auto=update

# Configuración de visibilidad SQL (Útil para que veas en consola lo que está pasando)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Puerto del servidor
server.port=8081

# Configuración de vistas (Thymeleaf)
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false


server.error.include-stacktrace=always

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

gemini.api.key=TU_API_KEY_AQUI